# Generated by Django 5.2.5 on 2025-08-27 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("author", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlogAuthor",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("author.author",),
        ),
        migrations.AlterField(
            model_name="author",
            name="bio",
            field=models.TextField(blank=True, null=True),
        ),
    ]
