# Generated by Django 5.2.5 on 2025-08-27 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("author", "0002_blogauthor_alter_author_bio"),
    ]

    operations = [
        migrations.AddField(
            model_name="author",
            name="demo_field",
            field=models.TextField(default="demo"),
        ),
    ]
