# Generated by Django 5.2.5 on 2025-08-27 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("author", "0002_blogauthor_alter_author_bio"),
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="author_blogs",
                to="author.author",
            ),
        ),
        migrations.CreateModel(
            name="CoverImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("image_link", models.URLField()),
                (
                    "blog",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="blog_ci",
                        to="blog.blog",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
