# Generated by Django 5.2.5 on 2025-08-28 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_demomodel_tags_remove_coverimage_blog_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blog",
            options={
                "permissions": [
                    ("update_title", "Can update the title of the blog"),
                    ("update_content", "Can update the content of blog"),
                ]
            },
        ),
        migrations.AlterModelOptions(
            name="tags",
            options={"ordering": ["name"]},
        ),
        migrations.AlterField(
            model_name="blog",
            name="cover_image",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="blog_cover_image",
                to="blog.coverimage",
            ),
        ),
        migrations.AlterField(
            model_name="blog",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="blog_tags", to="blog.tags"
            ),
        ),
    ]
